### ISSUE TITLE
2.0.0 Before Release To Dos

### ISSUE THREAD

**Issue by ke-d** [mrdokenny/Cookie-AutoDelete#156]
Version 2.X.X represents a huge change since it is rebuilt from almost scratch using React/Redux.

One of the bigger change is the white/grey lists are now expressions. It is now possible to use wildcards in the domain to match multiple domains and subdomains. 

`*.google.com` -> match google.com and subdomains
`google.com` -> match only google.com

For this reason, the popup will have a table showing how many expressions does that current domain. In the case of 2 or more "matched domains expressions", the first one will take priority. 

Also, whitelist will have a greater priority than the greylist. This makes #131 possible since you can add `*` in the greylist while whitelisting other domains.

This will happen on the update to 2.X.X. Your settings and lists will be migrated over to the new storage format of Redux. Because of this, the exported file for white/grey list of 1.X.X is NOT COMPATIBLE with 2.X.X.

"Enable Subdomain Check" is deprecated but will be used for the list migration.

This is a beta so expect bugs and untranslated text but it should be fine for daily use. Also note that there may be some problems in Container Mode with FF 55, but it works fine with it off. I'll probably bump the min version for FF to 56 (on AMO I can bump it from the developer page).

Resolved issues
#96
#113

To be closed on release of 2.X.X since the issue was created for 1.X.X and is unconfirmed for 2.X.X
#103 
#117 
#130 
#132 
#137 

Feel free to report bugs if it's not listed here.

Todo Development
- [x] Tweak phrasing for locales
- [x] Popup UI refresh #163
- [x] Expression Table UI refresh #161 
- [x] UI Refresh UI Bugs on Chromium
- [x] Rebump min version of FF to 56 for next beta version (problems with container mode)
- [x] Test and fix contextualIdentities events (Adding/Removing a Container)
- [x] Fix setting for Container Tabs Mode disappearing on a Restore Default Settings
- [x] Make the Expression List page more UI responsive
- [x] Revisit library functions for unexpected inputs

Todo Before Release
- [x] Wait for FF 56 to release
- [x] Update Version Notes
- [x] Update Locales
- [x] Update Description
- [x] Update Screenshots

**Comment by captainepoch** [comment]
FF 56 was released, so I think it's time to mark it as done

**Comment by ke-d** [comment]
@Primokorn @yfdyh000 @StoyanDimitrov @AdmiralAnimE @Riotism @eson57 @kostich @anthologist This is a general announcement in case you guys didn't know that Cookie AutoDelete is now using Crowdin for translations now.

https://crowdin.com/project/cookie-autodelete

**Comment by kostich** [comment]
@mrdokenny, great to hear!

I've completed the Serbian translation using the new platform.

**Comment by elsbrock** [comment]
I've updated the missing German messages.

**Comment by walrus543** [comment]
Thanks for letting us know.
Going to update the French strings ;)
