### ISSUE TITLE
CAD Enhancement/bugfix list

### ISSUE THREAD

**Issue by kennethtran93** [mrdokenny/Cookie-AutoDelete#595]
Reserving this issue for checking off what I have/will be doing. 

Feel free to subscribe to notifications on this issue for updates.

List of items that I plan to work upon soon, at the very least items that I could potentially work on more easily than others.  Just got my desktop linux refreshed after a while, so will need to get my development workflow back up again.

This list is not in order of what I will work on first.

- [x] Update dependencies (long overdue)
  - Released as v3.0.3
- [x] Automation, test, compiling (Travis CI stuff).
  - notes:  https://github.com/mozilla/sign-addon & https://github.com/mozilla/sign-addon/blob/master/.travis.yml
  - CI has transitioned from Travis to GitHub Actions.
  - PRs have been included in GitHub Actions test workflows.
  - Automated upload to Firefox and Chrome will begin with 3.2.0 (if the action workflow actually works).
- [ ] Export of small debugging info for copy-paste into GitHub Issues
  - CAD Version
  - Browser
  - Operating System (?)
  - 'Core' Settings
- [ ] Export of cleanup logs (maybe for debugging assistance?)
- [ ] Better import/export system (for multi-platform)
- [x] #567 Multiple Expression in one line ~/ reject comma-separated values...~
  - Fixed as of PR #652, released as of 3.1.1
- [x] #539 IP Regex Bug
  - Fixed as of PR #619, released as 3.0.4
- [x] #523 Chrome Localstorage
  - Initial Commit and Fix for Firefox too.  Will be released as 3.2.0
- [x] #521 white/grey from logs
- [ ] #527 Import via text file
- [x] #429 Export of 'Core' Settings
  - Added as of 3.3.0
- [x] #344 Purge expired cookies regardless of white/grey list (maybe).

**Comment by kennethtran93** [comment]
Happy New Year.  I have recently received publishing permissions on all official channels and will push out a much needed dependency upgrade first before addressing anything else (It may fall under pre-release in Github first as to test out after getting it approved on Chrome and Firefox).

**Comment by kennethtran93** [comment]
#615 is the final change for V3.0.3 for the time being.  

It has been officially released on Firefox on Jan 30, and Google Chrome  on Feb 3rd.

**Comment by swg0101** [comment]
Just got 3.0.3 on Chrome - now just waiting for localStorage support. Thanks! :)

**Comment by kennethtran93** [comment]
#619 fixes the #539 IP Regex bug.  Minor dependency update and added one nodejs library.

**Comment by kennethtran93** [comment]
V3.0.4 is now fully released on Firefox and Chrome.  This release was primarily to get CAD back into Mozilla's addon recommendation program.

**Comment by kennethtran93** [comment]
For those following along, the next release will add some numbers and texts to the popup and title.

![future_release_popup](https://user-images.githubusercontent.com/6724477/75604635-9b447700-5a8f-11ea-8e4f-30b3b0f59452.png)

If you haven't spotted them yet, they are as follows:
- Added Cookie Count for that domain into the BrowserAction Title (i.e. the text shown when you moueover the icon).  This will probably be more useful on Firefox Android.
- Title and Version added to popup, in addition to the Cookie Count.

Also as a bugfix, the cookie count number (badge icon text and elsewhere) should automatically update whenever a cookie matching that domain is added/removed.

As a sidenote, Translators will need to look at Crowdin again once I've uploaded the English version on it as there's some additions and minor revisions that were made.

**Comment by ghost** [comment]
@kennethtran93 why new file to translate on Crowdin?

![image](https://user-images.githubusercontent.com/886325/75907667-fa680a00-5e48-11ea-9f93-818fff2eee5b.png)

It looks similar - cannot be copied over old? (or other way around?)

**Comment by kennethtran93** [comment]
I am in the process of integrating Crowdin with GitHub. They should be the same file with some adjustments from recent releases. I will need to manually copy over strings for now.

**Comment by kennethtran93** [comment]
On second thought, I'm attempting a language mapping based on existing folders so hopefully less work needs to be done...

**Comment by kennethtran93** [comment]
Some translations needs manual copy paste and approval in Crowdin.  Follow #634 for a ton of commits that I'll squash down into one when it's more or less fully integrated.

A note for translators:  I've simply copied over and approved any translations given from the previous file.  That file will soon be removed.  In addition, I've attempted to take in some machine translations in hopes that it works out.  If it doesn't, please submit a new translation through Crowdin.

**Comment by kennethtran93** [comment]
With the amount of changes this time, I'm going to bump it up to 3.1
Main notables:
- Regular Expressions!
- Multiple expressions (separated by commas)!
- Cookie Count Updates
- Title and Version in Popup.

**Comment by kennethtran93** [comment]
3.2.0 Released.  LocalStorage for Chrome is the main item on hand.

**Comment by swg0101** [comment]
Still waiting for the app store to push this down :) Waiting patiently at the moment... 👍

**Comment by kennethtran93** [comment]
Forgot to update this - 3.3.0 released.
Main item of note related to the list is Core Setting Import/Export.
